### ISSUE TITLE
Nouvelle version

### ISSUE THREAD

**Issue by titouancreach** [uniteeio/dotnet-core-mailjet-client#14]
* [x] Possibilité de créer un "client" sans forcément l'injecter dans un service (pour les Azure Function)
* [x] Ne pas forcément lire la configuration depuis les `appsettings` (ou `IConfiguration`) et autoriser quelque chose comme:

```cs
  var client = new MailjetClient(pk: "xxxxxxxxxx", sk: "xxxxxxxxxx", senderName: "xxxxx@xx.xx");
```
* [ ] Ne plus utiliser NewtonSoft mais System.Text.Json
* [x] Code plus succint (C# 10)

**Comment by ReimuA** [comment]
https://github.com/uniteeio/dotnet-core-mailjet-client/pull/17#issue-1061028694
